/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student.login.dashboard;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import student.login.*;

/**
 *
 * @author shashank
 */
public class Create extends javax.swing.JFrame {

    /**
     * Creates new form Create
     */
    Student s;
    
    public Create(Student s) {
        initComponents();
        setTitle("Create");
        setLocationRelativeTo(null);
        setSize(950,620);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.s=s;
    }
    
//    public void trigger_date(){
//        UtilDateModel model = new UtilDateModel();
//        JDatePanelImpl datePanel = new JDatePanelImpl(model);
//        JDatePickerImpl datePicker = new JDatePickerImpl(datePanel);
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_create = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dashboard_create_reports = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        text_create_lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_create_fname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        date_create_dob = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        text_create_ph = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_create_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radiobtn_create_iti = new javax.swing.JRadioButton();
        radiobtn_create_diploma = new javax.swing.JRadioButton();
        radiobtn_create_grad = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        text_create_special = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        year_create_pass = new com.toedter.calendar.JYearChooser();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_create_expert = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        text_create_institute = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        text_create_paassmarks = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        text_create_obtainedmarks = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        text_create_totalmarks = new javax.swing.JTextField();
        btn_create_submit = new javax.swing.JButton();
        btn_create_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboard_create_reports.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        dashboard_create_reports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard_create_reports.setText("Reports");
        dashboard_create_reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel2.setBackground(new java.awt.Color(87, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Last Name :");

        text_create_lname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_create_lname.setAutoscrolls(false);
        text_create_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_create_lnameActionPerformed(evt);
            }
        });
        text_create_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_create_lnameKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("First Name :");

        text_create_fname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_create_fname.setAutoscrolls(false);
        text_create_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_create_fnameActionPerformed(evt);
            }
        });
        text_create_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_create_fnameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Date of Birth :");

        date_create_dob.setDateFormatString("y-MMM-dd");
        date_create_dob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Contact No. :");

        text_create_ph.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_create_ph.setAutoscrolls(false);
        text_create_ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_create_phActionPerformed(evt);
            }
        });
        text_create_ph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_create_phKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_create_phKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("E-mail :");

        text_create_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_create_email.setAutoscrolls(false);
        text_create_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_create_emailActionPerformed(evt);
            }
        });
        text_create_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_create_emailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_create_emailKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Qualification Type :");

        btngrp_create.add(radiobtn_create_iti);
        radiobtn_create_iti.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radiobtn_create_iti.setText("ITI");
        radiobtn_create_iti.setActionCommand("ITI");
        radiobtn_create_iti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radiobtn_create_iti.setName("ITI"); // NOI18N
        radiobtn_create_iti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_create_itiActionPerformed(evt);
            }
        });

        btngrp_create.add(radiobtn_create_diploma);
        radiobtn_create_diploma.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radiobtn_create_diploma.setText("Diploma");
        radiobtn_create_diploma.setActionCommand("Diploma");
        radiobtn_create_diploma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radiobtn_create_diploma.setName("Diploma"); // NOI18N

        btngrp_create.add(radiobtn_create_grad);
        radiobtn_create_grad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radiobtn_create_grad.setText("Graduation");
        radiobtn_create_grad.setActionCommand("Graduation");
        radiobtn_create_grad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radiobtn_create_grad.setName("Graduation"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Specialization :");

        text_create_special.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_create_special.setAutoscrolls(false);
        text_create_special.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_create_specialActionPerformed(evt);
            }
        });
        text_create_special.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_create_specialKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_create_specialKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Year of Passing :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Any Expertise :");

        text_create_expert.setColumns(20);
        text_create_expert.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_create_expert.setRows(5);
        jScrollPane1.setViewportView(text_create_expert);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Institution :");

        text_create_institute.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_create_institute.setAutoscrolls(false);
        text_create_institute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_create_instituteActionPerformed(evt);
            }
        });
        text_create_institute.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_create_instituteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_create_instituteKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Passing Marks :");

        text_create_paassmarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_create_paassmarks.setAutoscrolls(false);
        text_create_paassmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_create_paassmarksActionPerformed(evt);
            }
        });
        text_create_paassmarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_create_paassmarksKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_create_paassmarksKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Obtained Marks :");

        text_create_obtainedmarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_create_obtainedmarks.setAutoscrolls(false);
        text_create_obtainedmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_create_obtainedmarksActionPerformed(evt);
            }
        });
        text_create_obtainedmarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_create_obtainedmarksKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_create_obtainedmarksKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Total Marks :");

        text_create_totalmarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_create_totalmarks.setAutoscrolls(false);
        text_create_totalmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_create_totalmarksActionPerformed(evt);
            }
        });
        text_create_totalmarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_create_totalmarksKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_create_totalmarksKeyTyped(evt);
            }
        });

        btn_create_submit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_create_submit.setText("Submit");
        btn_create_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_create_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_create_submitActionPerformed(evt);
            }
        });

        btn_create_back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_create_back.setText("Back");
        btn_create_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_create_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_create_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(date_create_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_create_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_create_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(text_create_email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(text_create_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radiobtn_create_diploma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radiobtn_create_iti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radiobtn_create_grad))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_create_totalmarks)
                                    .addComponent(text_create_obtainedmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(year_create_pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_create_institute)
                                    .addComponent(text_create_paassmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(text_create_special, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_create_back, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btn_create_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radiobtn_create_iti)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(text_create_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37))
                                    .addComponent(text_create_fname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addComponent(date_create_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(text_create_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_create_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(year_create_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_create_institute, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_create_paassmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_create_obtainedmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_create_totalmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36)
                        .addComponent(radiobtn_create_diploma, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(radiobtn_create_grad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_create_special, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_create_back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_create_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashboard_create_reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(dashboard_create_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_create_specialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_specialKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_specialKeyTyped

    private void text_create_specialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_specialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_specialKeyPressed

    private void text_create_specialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_create_specialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_specialActionPerformed

    private void radiobtn_create_itiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_create_itiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_create_itiActionPerformed

    private void text_create_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_emailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_emailKeyTyped

    private void text_create_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_emailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_emailKeyPressed

    private void text_create_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_create_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_emailActionPerformed

    private void text_create_phKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_phKeyTyped
        // TODO add your handling code here:
        //        text_create_ph.addKeyListener(new KeyAdapter() {
            //            public void KeyPressed(KeyEvent ke){
                ////                String value = text_create_ph.getText();
                ////                int l = value.length();
                //                if(ke.getKeyChar() >= '0' && ke.getKeyChar()<='9')
                //                    text_create_ph.setEditable(true);
                //                else
                //                    text_create_ph.setEditable(false);
                //            }
            //        });
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
            text_create_ph.setEditable(true);
        else
            text_create_ph.setEditable(false);
    }//GEN-LAST:event_text_create_phKeyTyped

    private void text_create_phKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_phKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_phKeyPressed

    private void text_create_phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_create_phActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_phActionPerformed

    private void text_create_fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_fnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_fnameKeyPressed

    private void text_create_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_create_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_fnameActionPerformed

    private void text_create_lnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_lnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_lnameKeyPressed

    private void text_create_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_create_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_lnameActionPerformed

    private void text_create_instituteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_create_instituteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_instituteActionPerformed

    private void text_create_instituteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_instituteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_instituteKeyPressed

    private void text_create_instituteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_instituteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_instituteKeyTyped

    private void text_create_paassmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_create_paassmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_paassmarksActionPerformed

    private void text_create_paassmarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_paassmarksKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_paassmarksKeyPressed

    private void text_create_paassmarksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_paassmarksKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
            text_create_paassmarks.setEditable(true);
        else
            text_create_paassmarks.setEditable(false);
    }//GEN-LAST:event_text_create_paassmarksKeyTyped

    private void text_create_obtainedmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_create_obtainedmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_obtainedmarksActionPerformed

    private void text_create_obtainedmarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_obtainedmarksKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_obtainedmarksKeyPressed

    private void text_create_obtainedmarksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_obtainedmarksKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
            text_create_obtainedmarks.setEditable(true);
        else
            text_create_obtainedmarks.setEditable(false);
    }//GEN-LAST:event_text_create_obtainedmarksKeyTyped

    private void text_create_totalmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_create_totalmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_totalmarksActionPerformed

    private void text_create_totalmarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_totalmarksKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_create_totalmarksKeyPressed

    private void text_create_totalmarksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_create_totalmarksKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
            text_create_totalmarks.setEditable(true);
        else
            text_create_totalmarks.setEditable(false);
    }//GEN-LAST:event_text_create_totalmarksKeyTyped

    private void btn_create_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_create_backActionPerformed
        // TODO add your handling code here:
        dispose();
        new Dashboard(this.s).setVisible(true);
    }//GEN-LAST:event_btn_create_backActionPerformed

    private void btn_create_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_create_submitActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String lname = text_create_lname.getText();
        String fname = text_create_fname.getText();
        String dob = sdf.format(date_create_dob.getDate());
        String ph = text_create_ph.getText();
        String email = text_create_email.getText();
        String qual_type = btngrp_create.getSelection().getActionCommand();
//        String qual_type = (btngrp_create.getSelection() == radiobtn_create_iti)?radiobtn_create_iti.getText():((btngrp_create.getSelection() == radiobtn_create_diploma)?radiobtn_create_diploma.getText():radiobtn_create_grad.getText());
        String special = text_create_special.getText();
        String expert = text_create_expert.getText();
        String yop = String.valueOf(year_create_pass.getYear());
        String institute = text_create_institute.getText();
        int pass_marks = Integer.parseInt(text_create_paassmarks.getText());
        int obtained_marks = Integer.parseInt(text_create_obtainedmarks.getText());
        int total_marks = Integer.parseInt(text_create_totalmarks.getText());
        
        if(fname.isBlank() || dob.isBlank() || ph.isBlank() || email.isBlank() || qual_type.isBlank() || yop.isBlank() || institute.isBlank() || total_marks == 0)
            JOptionPane.showMessageDialog(this, "Incomplete fields", "Failed", JOptionPane.ERROR_MESSAGE);
        
        else if(!Pattern.compile("^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@" 
        + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$").matcher(email).matches())
            JOptionPane.showMessageDialog(this, "Incorrect email", "Failed", JOptionPane.ERROR_MESSAGE);
        
        else if(obtained_marks > total_marks && pass_marks > total_marks)
            JOptionPane.showMessageDialog(this, "Incorrect Marks", "Failed", JOptionPane.ERROR_MESSAGE);
        
        else if(ph.trim().length() != 10)
            JOptionPane.showMessageDialog(this, "Incorrect Contact number", "Failed", JOptionPane.ERROR_MESSAGE);
        
        else{
            Run_query run=new Run_query();
            try {
                int flag=run.run_create_query(lname, fname, dob, ph, email, qual_type, special, expert, yop, institute, pass_marks, obtained_marks, total_marks);
                
                switch (flag) {
                    case 1 -> {
                        JOptionPane.showMessageDialog(this, "Report Successfully added", "Success", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                        new Dashboard(this.s).setVisible(true);
                    }
                    case -1 -> JOptionPane.showMessageDialog(this, "Contact number or Email already exists", "Failed", JOptionPane.ERROR_MESSAGE);
                    default -> JOptionPane.showMessageDialog(this, "Failed to add Report", "Failed", JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (ParseException ex) {
                Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btn_create_submitActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Create().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create_back;
    private javax.swing.JButton btn_create_submit;
    private javax.swing.ButtonGroup btngrp_create;
    private javax.swing.JLabel dashboard_create_reports;
    private com.toedter.calendar.JDateChooser date_create_dob;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiobtn_create_diploma;
    private javax.swing.JRadioButton radiobtn_create_grad;
    private javax.swing.JRadioButton radiobtn_create_iti;
    private javax.swing.JTextField text_create_email;
    private javax.swing.JTextArea text_create_expert;
    private javax.swing.JTextField text_create_fname;
    private javax.swing.JTextField text_create_institute;
    private javax.swing.JTextField text_create_lname;
    private javax.swing.JTextField text_create_obtainedmarks;
    private javax.swing.JTextField text_create_paassmarks;
    private javax.swing.JTextField text_create_ph;
    private javax.swing.JTextField text_create_special;
    private javax.swing.JTextField text_create_totalmarks;
    private com.toedter.calendar.JYearChooser year_create_pass;
    // End of variables declaration//GEN-END:variables
}
