/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student.login.dashboard;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import student.login.*;

/**
 *
 * @author shashank
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    
    Student s;
    Report r;
    String pk_email;
    
    public Edit(Student s, Report r) throws ParseException {
        initComponents();
        setTitle("Edit");
//        setSize(950,620);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.s=s;
        this.r=r;
        fill_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @throws java.text.ParseException
     */
    
    public void fill_data() throws ParseException{
        
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy");
        
        text_edit_lname.setText(r.getLname());
        text_edit_fname.setText(r.getFname());
//        date_edit_dob.setDate(new java.sql.Date(Long.parseLong(r.getDob())));
        date_edit_dob.setDate(java.sql.Date.valueOf(r.getDob()));
        text_edit_ph.setText(r.getPh());
        text_edit_email.setText(r.getEmail());
        btngrp_edit.clearSelection();
        
        for(Enumeration<AbstractButton> buttons = btngrp_edit.getElements(); buttons.hasMoreElements();){
            AbstractButton btn = buttons.nextElement();
            if(btn.getActionCommand().equals(r.getQual())){
                btn.setSelected(true);
                break;
            } 
        }
        
//        Date date=sdf.parse(r.getYop());
        
        text_edit_special.setText(r.getSpecial());
        text_edit_expert.setText(r.getExp());
        year_edit_pass.setYear(Integer.parseInt(sdf.format((Date)sdf.parse(r.getYop())))); 
        text_edit_institute.setText(r.getInstitute());
        text_edit_passmarks.setText(String.valueOf(r.getPass_marks()));
        text_edit_obtainedmarks.setText(String.valueOf(r.getObtained_marks()));
        text_edit_totalmarks.setText(String.valueOf(r.getTotal_marks()));
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_edit = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dashboard_edit_reports = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        text_edit_lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_edit_fname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        date_edit_dob = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        text_edit_ph = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_edit_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radiobtn_edit_iti = new javax.swing.JRadioButton();
        radiobtn_edit_diploma = new javax.swing.JRadioButton();
        radiobtn_edit_grad = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        text_edit_special = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        year_edit_pass = new com.toedter.calendar.JYearChooser();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_edit_expert = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        text_edit_institute = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        text_edit_passmarks = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        text_edit_obtainedmarks = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        text_edit_totalmarks = new javax.swing.JTextField();
        btn_create_back = new javax.swing.JButton();
        btn_create_submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboard_edit_reports.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        dashboard_edit_reports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard_edit_reports.setText("Reports");
        dashboard_edit_reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel2.setBackground(new java.awt.Color(87, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Last Name :");

        text_edit_lname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_edit_lname.setAutoscrolls(false);
        text_edit_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_edit_lnameActionPerformed(evt);
            }
        });
        text_edit_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_edit_lnameKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("First Name :");

        text_edit_fname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_edit_fname.setAutoscrolls(false);
        text_edit_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_edit_fnameActionPerformed(evt);
            }
        });
        text_edit_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_edit_fnameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Date of Birth :");

        date_edit_dob.setDateFormatString("y-MMM-dd");
        date_edit_dob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Contact No. :");

        text_edit_ph.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_edit_ph.setAutoscrolls(false);
        text_edit_ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_edit_phActionPerformed(evt);
            }
        });
        text_edit_ph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_edit_phKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_edit_phKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("E-mail :");

        text_edit_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_edit_email.setAutoscrolls(false);
        text_edit_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_edit_emailActionPerformed(evt);
            }
        });
        text_edit_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_edit_emailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_edit_emailKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Qualification Type :");

        btngrp_edit.add(radiobtn_edit_iti);
        radiobtn_edit_iti.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radiobtn_edit_iti.setText("ITI");
        radiobtn_edit_iti.setActionCommand("ITI");
        radiobtn_edit_iti.setPreferredSize(new java.awt.Dimension(47, 30));
        radiobtn_edit_iti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_edit_itiActionPerformed(evt);
            }
        });

        btngrp_edit.add(radiobtn_edit_diploma);
        radiobtn_edit_diploma.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radiobtn_edit_diploma.setText("Diploma");
        radiobtn_edit_diploma.setActionCommand("Diploma");
        radiobtn_edit_diploma.setPreferredSize(new java.awt.Dimension(87, 30));

        btngrp_edit.add(radiobtn_edit_grad);
        radiobtn_edit_grad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radiobtn_edit_grad.setText("Graduation");
        radiobtn_edit_grad.setActionCommand("Graduation");
        radiobtn_edit_grad.setPreferredSize(new java.awt.Dimension(106, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Specialization :");

        text_edit_special.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_edit_special.setAutoscrolls(false);
        text_edit_special.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_edit_specialActionPerformed(evt);
            }
        });
        text_edit_special.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_edit_specialKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_edit_specialKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Year of Passing :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Any Expertise :");

        text_edit_expert.setColumns(20);
        text_edit_expert.setRows(5);
        jScrollPane1.setViewportView(text_edit_expert);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Institution :");

        text_edit_institute.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_edit_institute.setAutoscrolls(false);
        text_edit_institute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_edit_instituteActionPerformed(evt);
            }
        });
        text_edit_institute.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_edit_instituteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_edit_instituteKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Passing Marks :");

        text_edit_passmarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_edit_passmarks.setAutoscrolls(false);
        text_edit_passmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_edit_passmarksActionPerformed(evt);
            }
        });
        text_edit_passmarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_edit_passmarksKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_edit_passmarksKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Obtained Marks :");

        text_edit_obtainedmarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_edit_obtainedmarks.setAutoscrolls(false);
        text_edit_obtainedmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_edit_obtainedmarksActionPerformed(evt);
            }
        });
        text_edit_obtainedmarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_edit_obtainedmarksKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_edit_obtainedmarksKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Total Marks :");

        text_edit_totalmarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_edit_totalmarks.setAutoscrolls(false);
        text_edit_totalmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_edit_totalmarksActionPerformed(evt);
            }
        });
        text_edit_totalmarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_edit_totalmarksKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_edit_totalmarksKeyTyped(evt);
            }
        });

        btn_create_back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_create_back.setText("Back");
        btn_create_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_create_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_create_backActionPerformed(evt);
            }
        });

        btn_create_submit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_create_submit.setText("Submit");
        btn_create_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_create_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_create_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radiobtn_edit_diploma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radiobtn_edit_iti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radiobtn_edit_grad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(date_edit_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_edit_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_edit_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(text_edit_special, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_edit_email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_edit_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_edit_obtainedmarks)
                                            .addComponent(text_edit_totalmarks)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(year_edit_pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(text_edit_institute, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                .addComponent(text_edit_passmarks)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(btn_create_back, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(32, 32, 32)
                                            .addComponent(btn_create_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(10, 10, 10))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(year_edit_pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_edit_institute, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_edit_passmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_edit_obtainedmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_edit_totalmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_create_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_create_back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(text_edit_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_edit_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_edit_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(text_edit_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_edit_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radiobtn_edit_iti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiobtn_edit_diploma, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiobtn_edit_grad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_edit_special, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashboard_edit_reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(dashboard_edit_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_edit_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_edit_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_lnameActionPerformed

    private void text_edit_lnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_lnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_lnameKeyPressed

    private void text_edit_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_edit_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_fnameActionPerformed

    private void text_edit_fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_fnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_fnameKeyPressed

    private void text_edit_phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_edit_phActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_phActionPerformed

    private void text_edit_phKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_phKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_phKeyPressed

    private void text_edit_phKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_phKeyTyped
        // TODO add your handling code here:
        //        text_create_ph.addKeyListener(new KeyAdapter() {
            //            public void KeyPressed(KeyEvent ke){
                ////                String value = text_create_ph.getText();
                ////                int l = value.length();
                //                if(ke.getKeyChar() >= '0' && ke.getKeyChar()<='9')
                //                    text_create_ph.setEditable(true);
                //                else
                //                    text_create_ph.setEditable(false);
                //            }
            //        });
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
            text_edit_ph.setEditable(true);
        else
            text_edit_ph.setEditable(false);
    }//GEN-LAST:event_text_edit_phKeyTyped

    private void text_edit_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_edit_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_emailActionPerformed

    private void text_edit_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_emailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_emailKeyPressed

    private void text_edit_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_emailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_emailKeyTyped

    private void radiobtn_edit_itiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_edit_itiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_edit_itiActionPerformed

    private void text_edit_specialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_edit_specialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_specialActionPerformed

    private void text_edit_specialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_specialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_specialKeyPressed

    private void text_edit_specialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_specialKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_specialKeyTyped

    private void text_edit_instituteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_edit_instituteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_instituteActionPerformed

    private void text_edit_instituteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_instituteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_instituteKeyPressed

    private void text_edit_instituteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_instituteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_instituteKeyTyped

    private void text_edit_passmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_edit_passmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_passmarksActionPerformed

    private void text_edit_passmarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_passmarksKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_passmarksKeyPressed

    private void text_edit_passmarksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_passmarksKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
            text_edit_passmarks.setEditable(true);
        else
            text_edit_passmarks.setEditable(false);
    }//GEN-LAST:event_text_edit_passmarksKeyTyped

    private void text_edit_obtainedmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_edit_obtainedmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_obtainedmarksActionPerformed

    private void text_edit_obtainedmarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_obtainedmarksKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_obtainedmarksKeyPressed

    private void text_edit_obtainedmarksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_obtainedmarksKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
            text_edit_obtainedmarks.setEditable(true);
        else
            text_edit_obtainedmarks.setEditable(false);
    }//GEN-LAST:event_text_edit_obtainedmarksKeyTyped

    private void text_edit_totalmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_edit_totalmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_totalmarksActionPerformed

    private void text_edit_totalmarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_totalmarksKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edit_totalmarksKeyPressed

    private void text_edit_totalmarksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_edit_totalmarksKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
            text_edit_totalmarks.setEditable(true);
        else
            text_edit_totalmarks.setEditable(false);
    }//GEN-LAST:event_text_edit_totalmarksKeyTyped

    private void btn_create_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_create_backActionPerformed
        // TODO add your handling code here:
        dispose();
        new Dashboard(this.s).setVisible(true);
    }//GEN-LAST:event_btn_create_backActionPerformed

    private void btn_create_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_create_submitActionPerformed
        // TODO add your handling code here:
        pk_email=r.getEmail();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        r.setLname(text_edit_lname.getText());
        r.setFname(text_edit_fname.getText());
        r.setDob(sdf.format(date_edit_dob.getDate()));
        r.setPh(text_edit_ph.getText());
        r.setEmail(text_edit_email.getText());
        r.setQual(btngrp_edit.getSelection().getActionCommand());
        r.setSpecial(text_edit_special.getText());
        r.setExp(text_edit_expert.getText());
        r.setInstitute(text_edit_institute.getText());
        r.setYop(String.valueOf(year_edit_pass.getYear()));
        r.setPass_marks(Integer.parseInt(text_edit_passmarks.getText()));
        r.setObtained_marks(Integer.parseInt(text_edit_obtainedmarks.getText()));
        r.setTotal_marks(Integer.parseInt(text_edit_totalmarks.getText()));
        
        if(r.getFname().isBlank() || r.getDob().isBlank() || r.getPh().isBlank() || r.getEmail().isBlank() || r.getQual().isBlank() || r.getYop().isBlank() || r.getInstitute().isBlank() || r.getTotal_marks() == 0)
            JOptionPane.showMessageDialog(this, "Incomplete fields", "Failed", JOptionPane.ERROR_MESSAGE);
        
        else if(!Pattern.compile("^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@" 
        + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$").matcher(r.getEmail()).matches())
            JOptionPane.showMessageDialog(this, "Incorrect email", "Failed", JOptionPane.ERROR_MESSAGE);
        
        else if(r.getObtained_marks() > r.getTotal_marks() && r.getPass_marks()> r.getTotal_marks())
            JOptionPane.showMessageDialog(this, "Incorrect Marks", "Failed", JOptionPane.ERROR_MESSAGE);
        
        else if(r.getPh().trim().length() != 10)
            JOptionPane.showMessageDialog(this, "Incorrect Contact number", "Failed", JOptionPane.ERROR_MESSAGE);
        
        else{
            Run_query run=new Run_query();
            try {
                int flag=run.run_edit_update_query(r,pk_email);
                
                switch (flag) {
                    case 1 -> {
                        JOptionPane.showMessageDialog(this, "Report Successfully Updated", "Success", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                        new Dashboard(this.s).setVisible(true);
                    }
                    case -1 -> JOptionPane.showMessageDialog(this, "Contact number or Email already exists", "Failed", JOptionPane.ERROR_MESSAGE);
                    default -> JOptionPane.showMessageDialog(this, "Failed to add Report", "Failed", JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (ParseException ex) {
                Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btn_create_submitActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Edit().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create_back;
    private javax.swing.JButton btn_create_submit;
    private javax.swing.ButtonGroup btngrp_edit;
    private javax.swing.JLabel dashboard_edit_reports;
    private com.toedter.calendar.JDateChooser date_edit_dob;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiobtn_edit_diploma;
    private javax.swing.JRadioButton radiobtn_edit_grad;
    private javax.swing.JRadioButton radiobtn_edit_iti;
    private javax.swing.JTextField text_edit_email;
    private javax.swing.JTextArea text_edit_expert;
    private javax.swing.JTextField text_edit_fname;
    private javax.swing.JTextField text_edit_institute;
    private javax.swing.JTextField text_edit_lname;
    private javax.swing.JTextField text_edit_obtainedmarks;
    private javax.swing.JTextField text_edit_passmarks;
    private javax.swing.JTextField text_edit_ph;
    private javax.swing.JTextField text_edit_special;
    private javax.swing.JTextField text_edit_totalmarks;
    private com.toedter.calendar.JYearChooser year_edit_pass;
    // End of variables declaration//GEN-END:variables
}
