/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student.login.dashboard;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.WindowConstants;
import student.login.Student;

/**
 *
 * @author shashank
 */
public class Report_display extends javax.swing.JFrame {

    /**
     * Creates new form Report_display
     */
    
    Report r;
    Student s;
    
    public Report_display(Student s, Report r) throws ParseException {
        initComponents();
        setTitle("Display Report");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.r=r;
        this.s=s;
        fill_data();
    }
    
    public void fill_data() throws ParseException{
        
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy");
        
        text_display_lname.setText(r.getLname());
        text_display_fname.setText(r.getFname());
//        date_edit_dob.setDate(new java.sql.Date(Long.parseLong(r.getDob())));
        date_display_dob.setDate(java.sql.Date.valueOf(r.getDob()));
        text_display_ph.setText(r.getPh());
        text_display_email.setText(r.getEmail());
        btngrp_display.clearSelection();
        
        for(Enumeration<AbstractButton> buttons = btngrp_display.getElements(); buttons.hasMoreElements();){
            AbstractButton btn = buttons.nextElement();
            if(btn.getActionCommand().equals(r.getQual())){
                btn.setSelected(true);
                break;
            } 
        }
        
//        Date date=sdf.parse(r.getYop());
        
        text_display_special.setText(r.getSpecial());
        text_display_expert.setText(r.getExp());
        year_display_pass.setYear(Integer.parseInt(sdf.format((Date)sdf.parse(r.getYop())))); 
        text_display_institute.setText(r.getInstitute());
        text_display_passmarks.setText(String.valueOf(r.getPass_marks()));
        text_display_obtainedmarks.setText(String.valueOf(r.getObtained_marks()));
        text_display_totalmarks.setText(String.valueOf(r.getTotal_marks()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_display = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dashboard_edit_reports = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        text_display_lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_display_fname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        date_display_dob = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        text_display_ph = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_display_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radiobtn_display_iti = new javax.swing.JRadioButton();
        radiobtn_display_diploma = new javax.swing.JRadioButton();
        radiobtn_display_grad = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        text_display_special = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        year_display_pass = new com.toedter.calendar.JYearChooser();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_display_expert = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        text_display_institute = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        text_display_passmarks = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        text_display_obtainedmarks = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        text_display_totalmarks = new javax.swing.JTextField();
        btn_display_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboard_edit_reports.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        dashboard_edit_reports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard_edit_reports.setText("Reports");
        dashboard_edit_reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel2.setBackground(new java.awt.Color(87, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Last Name :");

        text_display_lname.setEditable(false);
        text_display_lname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_display_lname.setAutoscrolls(false);
        text_display_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_display_lnameActionPerformed(evt);
            }
        });
        text_display_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_display_lnameKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("First Name :");

        text_display_fname.setEditable(false);
        text_display_fname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_display_fname.setAutoscrolls(false);
        text_display_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_display_fnameActionPerformed(evt);
            }
        });
        text_display_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_display_fnameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Date of Birth :");

        date_display_dob.setDateFormatString("y-MMM-dd");
        date_display_dob.setEnabled(false);
        date_display_dob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Contact No. :");

        text_display_ph.setEditable(false);
        text_display_ph.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_display_ph.setAutoscrolls(false);
        text_display_ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_display_phActionPerformed(evt);
            }
        });
        text_display_ph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_display_phKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_display_phKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("E-mail :");

        text_display_email.setEditable(false);
        text_display_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_display_email.setAutoscrolls(false);
        text_display_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_display_emailActionPerformed(evt);
            }
        });
        text_display_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_display_emailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_display_emailKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Qualification Type :");

        btngrp_display.add(radiobtn_display_iti);
        radiobtn_display_iti.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radiobtn_display_iti.setText("ITI");
        radiobtn_display_iti.setActionCommand("ITI");
        radiobtn_display_iti.setEnabled(false);
        radiobtn_display_iti.setPreferredSize(new java.awt.Dimension(47, 30));
        radiobtn_display_iti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_display_itiActionPerformed(evt);
            }
        });

        btngrp_display.add(radiobtn_display_diploma);
        radiobtn_display_diploma.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radiobtn_display_diploma.setText("Diploma");
        radiobtn_display_diploma.setActionCommand("Diploma");
        radiobtn_display_diploma.setEnabled(false);
        radiobtn_display_diploma.setPreferredSize(new java.awt.Dimension(87, 30));

        btngrp_display.add(radiobtn_display_grad);
        radiobtn_display_grad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radiobtn_display_grad.setText("Graduation");
        radiobtn_display_grad.setActionCommand("Graduation");
        radiobtn_display_grad.setEnabled(false);
        radiobtn_display_grad.setPreferredSize(new java.awt.Dimension(106, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Specialization :");

        text_display_special.setEditable(false);
        text_display_special.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_display_special.setAutoscrolls(false);
        text_display_special.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_display_specialActionPerformed(evt);
            }
        });
        text_display_special.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_display_specialKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_display_specialKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Year of Passing :");

        year_display_pass.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Any Expertise :");

        text_display_expert.setEditable(false);
        text_display_expert.setColumns(20);
        text_display_expert.setRows(5);
        jScrollPane1.setViewportView(text_display_expert);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Institution :");

        text_display_institute.setEditable(false);
        text_display_institute.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_display_institute.setAutoscrolls(false);
        text_display_institute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_display_instituteActionPerformed(evt);
            }
        });
        text_display_institute.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_display_instituteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_display_instituteKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Passing Marks :");

        text_display_passmarks.setEditable(false);
        text_display_passmarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_display_passmarks.setAutoscrolls(false);
        text_display_passmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_display_passmarksActionPerformed(evt);
            }
        });
        text_display_passmarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_display_passmarksKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_display_passmarksKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Obtained Marks :");

        text_display_obtainedmarks.setEditable(false);
        text_display_obtainedmarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_display_obtainedmarks.setAutoscrolls(false);
        text_display_obtainedmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_display_obtainedmarksActionPerformed(evt);
            }
        });
        text_display_obtainedmarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_display_obtainedmarksKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_display_obtainedmarksKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Total Marks :");

        text_display_totalmarks.setEditable(false);
        text_display_totalmarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_display_totalmarks.setAutoscrolls(false);
        text_display_totalmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_display_totalmarksActionPerformed(evt);
            }
        });
        text_display_totalmarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_display_totalmarksKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_display_totalmarksKeyTyped(evt);
            }
        });

        btn_display_back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_display_back.setText("Back");
        btn_display_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_display_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_display_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radiobtn_display_diploma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radiobtn_display_iti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radiobtn_display_grad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(date_display_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_display_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_display_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(text_display_special, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_display_back, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_display_email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_display_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_display_obtainedmarks, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(text_display_totalmarks)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(year_display_pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(text_display_institute, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(text_display_passmarks))))))
                        .addGap(10, 10, 10))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(year_display_pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_display_institute, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_display_passmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_display_obtainedmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_display_totalmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(text_display_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_display_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_display_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(text_display_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_display_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radiobtn_display_iti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiobtn_display_diploma, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiobtn_display_grad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_display_special, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_display_back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashboard_edit_reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(dashboard_edit_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_display_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_display_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_lnameActionPerformed

    private void text_display_lnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_lnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_lnameKeyPressed

    private void text_display_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_display_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_fnameActionPerformed

    private void text_display_fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_fnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_fnameKeyPressed

    private void text_display_phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_display_phActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_phActionPerformed

    private void text_display_phKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_phKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_phKeyPressed

    private void text_display_phKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_phKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_phKeyTyped

    private void text_display_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_display_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_emailActionPerformed

    private void text_display_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_emailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_emailKeyPressed

    private void text_display_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_emailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_emailKeyTyped

    private void radiobtn_display_itiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_display_itiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_display_itiActionPerformed

    private void text_display_specialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_display_specialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_specialActionPerformed

    private void text_display_specialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_specialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_specialKeyPressed

    private void text_display_specialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_specialKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_specialKeyTyped

    private void text_display_instituteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_display_instituteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_instituteActionPerformed

    private void text_display_instituteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_instituteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_instituteKeyPressed

    private void text_display_instituteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_instituteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_instituteKeyTyped

    private void text_display_passmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_display_passmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_passmarksActionPerformed

    private void text_display_passmarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_passmarksKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_passmarksKeyPressed

    private void text_display_passmarksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_passmarksKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_passmarksKeyTyped

    private void text_display_obtainedmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_display_obtainedmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_obtainedmarksActionPerformed

    private void text_display_obtainedmarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_obtainedmarksKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_obtainedmarksKeyPressed

    private void text_display_obtainedmarksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_obtainedmarksKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_obtainedmarksKeyTyped

    private void text_display_totalmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_display_totalmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_totalmarksActionPerformed

    private void text_display_totalmarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_totalmarksKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_totalmarksKeyPressed

    private void text_display_totalmarksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_display_totalmarksKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_display_totalmarksKeyTyped

    private void btn_display_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_display_backActionPerformed
        // TODO add your handling code here:
        dispose();
        new Reports_frame(this.s).setVisible(true);
    }//GEN-LAST:event_btn_display_backActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Report_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Report_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Report_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Report_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Report_display().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_display_back;
    private javax.swing.ButtonGroup btngrp_display;
    private javax.swing.JLabel dashboard_edit_reports;
    private com.toedter.calendar.JDateChooser date_display_dob;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiobtn_display_diploma;
    private javax.swing.JRadioButton radiobtn_display_grad;
    private javax.swing.JRadioButton radiobtn_display_iti;
    private javax.swing.JTextField text_display_email;
    private javax.swing.JTextArea text_display_expert;
    private javax.swing.JTextField text_display_fname;
    private javax.swing.JTextField text_display_institute;
    private javax.swing.JTextField text_display_lname;
    private javax.swing.JTextField text_display_obtainedmarks;
    private javax.swing.JTextField text_display_passmarks;
    private javax.swing.JTextField text_display_ph;
    private javax.swing.JTextField text_display_special;
    private javax.swing.JTextField text_display_totalmarks;
    private com.toedter.calendar.JYearChooser year_display_pass;
    // End of variables declaration//GEN-END:variables
}
